## Introdução à Camada Gold

 iniciar a camada Gold utilizando os dados tratados da camada Silver.

 transformar os dados tratados em informações organizadas e indicadores preparados para análise e visualização.

# 1. Importação da biblioteca Pandas e  Carregamento dos dados da camada Silver
 
 importar a biblioteca Pandas.

 carregar o arquivo `Leitos_2026_RJ_tratado.csv`.

 utilizar suas funções para carregar, manipular, agrupar e analisar os dados hospitalares.

 utilizar os dados tratados como base para construir a camada Gold.

In [58]:
import pandas as pd
hospi_gold = pd.read_csv(r'C:\Users\lokiz\OneDrive\Documentos\projeto_hospitalar_rio\02_SILVER\leitos_2026_RJ_tratado.csv')
hospi_gold

,COMP,REGIAO,UF,CO_IBGE,MUNICIPIO,CNES,NOME_ESTABELECIMENTO,RAZAO_SOCIAL,TP_GESTAO,CO_TIPO_UNIDADE,...,UTI_ADULTO_EXIST,UTI_ADULTO_SUS,UTI_PEDIATRICO_EXIST,UTI_PEDIATRICO_SUS,UTI_NEONATAL_EXIST,UTI_NEONATAL_SUS,UTI_QUEIMADO_EXIST,UTI_QUEIMADO_SUS,UTI_CORONARIANA_EXIST,UTI_CORONARIANA_SUS
0,202601,SUDESTE,RJ,330330,NITEROI,12505,HOSPITAL UNIVERSITARIO ANTONIO PEDRO,EMPRESA BRASILEIRA DE SERVICOS HOSPITALARES,M,5,...,16,16,0,0,8,8,0,0,10,10
1,202601,SUDESTE,RJ,330330,NITEROI,12513,HOSPITAL MUNICIPAL CARLOS TORTELLY,FUNDACAO MUNICIPAL DE SAUDE,M,5,...,0,0,0,0,0,0,0,0,0,0
2,202601,SUDESTE,RJ,330330,NITEROI,12521,SES RJ HOSPITAL ESTADUAL AZEVEDO LIMA,SECRETARIA DE ESTADO DE SAUDE SES,E,5,...,35,30,0,0,10,0,0,0,0,0
3,202601,SUDESTE,RJ,330330,NITEROI,12548,HOSPITAL DA POLICIA MILITAR DE NITEROI,HOSPITAL DA POLICIA MILITAR DE NITEROI,M,5,...,0,0,0,0,0,0,0,0,0,0
4,202601,SUDESTE,RJ,330330,NITEROI,12556,HOSPITAL ORENCIO DE FREITAS,FUNDACAO MUNICIPAL DE SAUDE DE NITEROI,M,5,...,6,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2959,202606,SUDESTE,RJ,330330,NITEROI,9839674,ESSENCIAL HOSPITAL DE TRANSICAO,ESSENCIAL CARE ASSISTENCIA MEDICA,M,5,...,0,0,0,0,0,0,0,0,0,0
2960,202606,SUDESTE,RJ,330270,MARICA,9895124,ERNESTO CHE GUEVARA SMSM,HOSPITAL MUNICIPAL DR ERNESTO CHE GUEVARA,M,5,...,20,10,5,0,0,0,0,0,0,0
2961,202606,SUDESTE,RJ,330010,ANGRA DOS REIS,9903496,PLAZA MEDICAL SERVICOS ESPECIALIZADOS EM SAUDE...,PLAZA MEDICAL SERVICOS ESPECIALIZADOS EM SAUDE...,M,5,...,0,0,5,0,15,0,0,0,0,0
2962,202606,SUDESTE,RJ,330490,SAO GONCALO,9912584,CLISSIL,CLISSIL CLINICA SAO SILVESTRE,M,7,...,0,0,0,0,0,0,0,0,0,0
2963,202606,SUDESTE,RJ,330110,CANTAGALO,9921710,CTI JOAO PAULO II,CENTRO DE TRATAMENTO INTENSIVO DE CANTAGALO LTDA,M,5,...,10,0,0,0,0,0,0,0,0,0

# 2. Visualização dos primeiros registros

 visualizando as primeiras linhas dos dados.

 confirmando que o arquivo da Silver foi carregado corretamente.

In [59]:
hospi_gold.head()

,COMP,REGIAO,UF,CO_IBGE,MUNICIPIO,CNES,NOME_ESTABELECIMENTO,RAZAO_SOCIAL,TP_GESTAO,CO_TIPO_UNIDADE,...,UTI_ADULTO_EXIST,UTI_ADULTO_SUS,UTI_PEDIATRICO_EXIST,UTI_PEDIATRICO_SUS,UTI_NEONATAL_EXIST,UTI_NEONATAL_SUS,UTI_QUEIMADO_EXIST,UTI_QUEIMADO_SUS,UTI_CORONARIANA_EXIST,UTI_CORONARIANA_SUS
0,202601,SUDESTE,RJ,330330,NITEROI,12505,HOSPITAL UNIVERSITARIO ANTONIO PEDRO,EMPRESA BRASILEIRA DE SERVICOS HOSPITALARES,M,5,...,16,16,0,0,8,8,0,0,10,10
1,202601,SUDESTE,RJ,330330,NITEROI,12513,HOSPITAL MUNICIPAL CARLOS TORTELLY,FUNDACAO MUNICIPAL DE SAUDE,M,5,...,0,0,0,0,0,0,0,0,0,0
2,202601,SUDESTE,RJ,330330,NITEROI,12521,SES RJ HOSPITAL ESTADUAL AZEVEDO LIMA,SECRETARIA DE ESTADO DE SAUDE SES,E,5,...,35,30,0,0,10,0,0,0,0,0
3,202601,SUDESTE,RJ,330330,NITEROI,12548,HOSPITAL DA POLICIA MILITAR DE NITEROI,HOSPITAL DA POLICIA MILITAR DE NITEROI,M,5,...,0,0,0,0,0,0,0,0,0,0
4,202601,SUDESTE,RJ,330330,NITEROI,12556,HOSPITAL ORENCIO DE FREITAS,FUNDACAO MUNICIPAL DE SAUDE DE NITEROI,M,5,...,6,0,0,0,0,0,0,0,0,0

# 3. Verificação da dimensão dos dados

 verificando a quantidade de linhas e colunas.

 conhecendo o tamanho do conjunto de dados que será utilizado na camada Gold.

In [60]:
hospi_gold.shape

(2964, 34)

# 4. Identificação das colunas da Gold

* visualizar todos os nomes das colunas disponíveis no conjunto de dados da camada Gold.

 conhecendo exatamente quais informações estão disponíveis para criar os indicadores e análises hospitalares, evitando utilizar nomes de colunas incorretos.

In [61]:
hospi_gold.columns.tolist()

['COMP',
 'REGIAO',
 'UF',
 'CO_IBGE',
 'MUNICIPIO',
 'CNES',
 'NOME_ESTABELECIMENTO',
 'RAZAO_SOCIAL',
 'TP_GESTAO',
 'CO_TIPO_UNIDADE',
 'DS_TIPO_UNIDADE',
 'NATUREZA_JURIDICA',
 'DESC_NATUREZA_JURIDICA',
 'NO_LOGRADOURO',
 'NU_ENDERECO',
 'NO_COMPLEMENTO',
 'NO_BAIRRO',
 'CO_CEP',
 'NU_TELEFONE',
 'NO_EMAIL',
 'LEITOS_EXISTENTES',
 'LEITOS_SUS',
 'UTI_TOTAL_EXIST',
 'UTI_TOTAL_SUS',
 'UTI_ADULTO_EXIST',
 'UTI_ADULTO_SUS',
 'UTI_PEDIATRICO_EXIST',
 'UTI_PEDIATRICO_SUS',
 'UTI_NEONATAL_EXIST',
 'UTI_NEONATAL_SUS',
 'UTI_QUEIMADO_EXIST',
 'UTI_QUEIMADO_SUS',
 'UTI_CORONARIANA_EXIST',
 'UTI_CORONARIANA_SUS']

# 5.Identificação das colunas numéricas

 identificação de quais colunas possuem dados numéricos.

encontrar os campos que podem ser utilizados em cálculos e indicadores.

In [62]:
hospi_gold.select_dtypes(include='number').columns.tolist()

['COMP',
 'CO_IBGE',
 'CNES',
 'CO_TIPO_UNIDADE',
 'NATUREZA_JURIDICA',
 'CO_CEP',
 'LEITOS_EXISTENTES',
 'LEITOS_SUS',
 'UTI_TOTAL_EXIST',
 'UTI_TOTAL_SUS',
 'UTI_ADULTO_EXIST',
 'UTI_ADULTO_SUS',
 'UTI_PEDIATRICO_EXIST',
 'UTI_PEDIATRICO_SUS',
 'UTI_NEONATAL_EXIST',
 'UTI_NEONATAL_SUS',
 'UTI_QUEIMADO_EXIST',
 'UTI_QUEIMADO_SUS',
 'UTI_CORONARIANA_EXIST',
 'UTI_CORONARIANA_SUS']

# 6 Estatísticas dos leitos existentes

 analisando  estatisticamente a coluna de leitos existentes.

 entendendo a distribuição dos leitos entre os estabelecimentos.

In [63]:
hospi_gold['LEITOS_EXISTENTES'].describe()

count    2964.000000
mean       89.136302
std        90.045766
min         1.000000
25%        31.000000
50%        61.000000
75%       112.000000
max       561.000000
Name: LEITOS_EXISTENTES, dtype: float64

# 7. Total de leitos existentes

calculando a quantidade total de leitos existentes na base.

 obtendo uma visão geral da capacidade de leitos dos estabelecimentos analisados.

In [64]:
total_leitos = hospi_gold['LEITOS_EXISTENTES'].sum()
total_leitos

np.int64(264200)

# 8. Total de leitos SUS

 calculando a quantidade total de leitos destinados ao SUS.

 medir a capacidade de atendimento pelo SUS na base analisada.

In [65]:
total_leitos_sus = hospi_gold['LEITOS_SUS'].sum()
total_leitos_sus

np.int64(145005)

# 9. Comparação entre leitos existentes e leitos SUS

 criando uma tabela comparando o total de leitos existentes com o total de leitos SUS.

 facilitar a interpretação da capacidade total e da parcela destinada ao SUS.

In [66]:
comparação_de_leitos = pd.DataFrame({
    'TIPO':[
        'LEITOS EXISTENTES',
        'LEITOS SUS'
    ],
    'QUANTIDADE':[
        hospi_gold['LEITOS_EXISTENTES'].sum(),
        hospi_gold['LEITOS_SUS'].sum()
    ]
})

comparação_de_leitos

                TIPO  QUANTIDADE
0  LEITOS EXISTENTES      264200
1         LEITOS SUS      145005

# 10. Percentual de leitos SUS

 calculando o percentual de leitos destinados ao SUS em relação ao total de leitos existentes.

 identificando qual proporção da capacidade total de leitos está destinada ao atendimento pelo SUS.

In [67]:
percentual_leitos_sus = (
    total_leitos_sus / total_leitos
) * 100

percentual_leitos_sus = round(percentual_leitos_sus, 2)

percentual_leitos_sus

np.float64(54.88)

# 11. Análise de leitos por município

 calculando a quantidade total de leitos existentes em cada município.

 identificando quais municípios concentram a maior quantidade de leitos hospitalares no Rio de Janeiro.

In [68]:
leitos_por_municipio = (
    hospi_gold
    .groupby("MUNICIPIO")["LEITOS_EXISTENTES"]
    .sum()
    .sort_values(ascending=False)
)

leitos_por_municipio

MUNICIPIO
RIO DE JANEIRO           121358
NITEROI                   17361
CAMPOS DOS GOYTACAZES     12164
DUQUE DE CAXIAS            9868
PETROPOLIS                 9358
                          ...
CONCEICAO DE MACABU         126
AREAL                       120
SAPUCAIA                    108
TANGUA                       84
CARAPEBUS                    32
Name: LEITOS_EXISTENTES, Length: 87, dtype: int64

# 12. Top 10 municípios com mais leitos

 selecionanda os 10 municípios que possuem a maior quantidade de leitos existentes.

 destacando os municípios com maior capacidade hospitalar e facilitar a análise dos principais resultados.

In [69]:
top_10_leitos_municipio = leitos_por_municipio.head(10)

top_10_leitos_municipio

MUNICIPIO
RIO DE JANEIRO           121358
NITEROI                   17361
CAMPOS DOS GOYTACAZES     12164
DUQUE DE CAXIAS            9868
PETROPOLIS                 9358
NOVA IGUACU                8710
VOLTA REDONDA              7018
SAO GONCALO                6216
MACAE                      4326
NOVA FRIBURGO              3894
Name: LEITOS_EXISTENTES, dtype: int64

# 13. Análise de leitos SUS por município

calculando a quantidade total de leitos destinados ao SUS em cada município.

 identificar quais municípios possuem a maior quantidade de leitos disponíveis para atendimento pelo SUS.

In [70]:
leitos_sus_por_municipio = (
    hospi_gold
    .groupby("MUNICIPIO")["LEITOS_SUS"]
    .sum()
    .sort_values(ascending=False)
)

leitos_sus_por_municipio

MUNICIPIO
RIO DE JANEIRO               58128
CAMPOS DOS GOYTACAZES         7208
NITEROI                       6557
DUQUE DE CAXIAS               6186
NOVA IGUACU                   4657
                             ...
SAPUCAIA                       108
TANGUA                          84
CARAPEBUS                       32
ITALVA                           0
COMENDADOR LEVY GASPARIAN        0
Name: LEITOS_SUS, Length: 87, dtype: int64

# 14. Top 10 municípios em leitos SUS

 selecionar os 10 municípios com maior quantidade de leitos destinados ao SUS.

 criando um ranking dos municípios com maior capacidade de atendimento hospitalar pelo SUS.

In [71]:
top_10_leitos_sus_municipio = total_sus_por_municipio.head(10)

top_10_leitos_sus_municipio

MUNICIPIO
RIO DE JANEIRO           58128
CAMPOS DOS GOYTACAZES     7208
NITEROI                   6557
DUQUE DE CAXIAS           6186
NOVA IGUACU               4657
SAO GONCALO               4410
PETROPOLIS                4336
VOLTA REDONDA             3654
VASSOURAS                 2352
NOVA FRIBURGO             2334
Name: LEITOS_SUS, dtype: int64

# 15. Leitos existentes por tipo de estabelecimento

 calculando a quantidade total de leitos existentes para cada tipo de estabelecimento hospitalar.

 identificar quais tipos de unidades concentram a maior quantidade de leitos hospitalares.

In [72]:
leitos_por_tipo = (
    hospi_gold
    .groupby("DS_TIPO_UNIDADE")["LEITOS_EXISTENTES"]
    .sum()
    .sort_values(ascending=False)
)

leitos_por_tipo

DS_TIPO_UNIDADE
HOSPITAL GERAL                  211324
HOSPITAL ESPECIALIZADO           50858
PRONTO SOCORRO GERAL              1494
UNIDADE MISTA                      392
PRONTO SOCORRO ESPECIALIZADO       132
Name: LEITOS_EXISTENTES, dtype: int64

# 16. Leitos SUS por tipo de estabelecimento

 calculando a quantidade total de leitos destinados ao SUS para cada tipo de estabelecimento.

 identificar quais tipos de unidades concentram a maior quantidade de leitos disponíveis para atendimento pelo SUS.

In [73]:
leitos_sus_por_tipo = (
    hospi_gold
    .groupby("DS_TIPO_UNIDADE")["LEITOS_SUS"]
    .sum()
    .sort_values(ascending=False)
)

leitos_sus_por_tipo

DS_TIPO_UNIDADE
HOSPITAL GERAL                  112757
HOSPITAL ESPECIALIZADO           30820
PRONTO SOCORRO GERAL              1374
UNIDADE MISTA                       54
PRONTO SOCORRO ESPECIALIZADO         0
Name: LEITOS_SUS, dtype: int64

# 17. Análise do total de UTI

 calculando a quantidade total de leitos de UTI existentes nos estabelecimentos analisados.

 identificar a capacidade de atendimento em terapia intensiva e criar um indicador importante da estrutura hospitalar.

In [74]:
total_uti = int(hospi_gold["UTI_TOTAL_EXIST"].sum())

total_uti

48954

# 18. Total de UTI destinadas ao SUS

calculando a quantidade total de leitos de UTI destinados ao SUS.

 identificar a capacidade de terapia intensiva disponível para atendimento pelo SUS nos estabelecimentos analisados.

In [75]:
total_uti_sus = int(hospi_gold["UTI_TOTAL_SUS"].sum())

total_uti_sus

14420

# 19. Percentual de UTI SUS

 calculando o percentual de leitos de UTI destinados ao SUS em relação ao total de leitos de UTI existentes.

 entender a participação das UTIs SUS dentro da capacidade total de terapia intensiva dos estabelecimentos analisados.

In [76]:
percentual_uti_sus = (
    total_uti_sus / total_uti
) * 100

percentual_uti_sus = round(percentual_uti_sus, 2)

percentual_uti_sus

29.46

# 20. UTI adulto existente

 calculando a quantidade total de leitos de UTI adulto existentes nos estabelecimentos analisados.

 identificar a capacidade hospitalar destinada ao atendimento intensivo de pacientes adultos.

In [77]:
total_uti_adulto = int(
    hospi_gold["UTI_ADULTO_EXIST"].sum()
)

total_uti_adulto

33748

# 21. UTI adulto SUS

 calculando a quantidade total de leitos de UTI adulto destinados ao SUS.

 identificar a capacidade de terapia intensiva para pacientes adultos disponível para atendimento pelo SUS.

In [78]:
total_uti_adulto_sus = int(
    hospi_gold["UTI_ADULTO_SUS"].sum()
)

total_uti_adulto_sus

10696

# 22. Percentual de UTI adulto SUS

 calculando  o percentual de leitos de UTI adulto destinados ao SUS em relação ao total de UTI adulto existente.

 entender a participação do SUS na capacidade de atendimento de terapia intensiva para pacientes adultos.

In [79]:
percentual_uti_adulto_sus = (
    total_uti_adulto_sus / total_uti_adulto
) * 100

percentual_uti_adulto_sus = round(
    percentual_uti_adulto_sus, 2
)

percentual_uti_adulto_sus

31.69

# 23. UTI pediátrica existente

 calculando a quantidade total de leitos de UTI pediátrica existentes nos estabelecimentos analisados.

 identificando a capacidade hospitalar destinada ao atendimento intensivo de pacientes pediátricos.

In [80]:
total_uti_pediatrica = int(
    hospi_gold['UTI_PEDIATRICO_EXIST'].sum()
)

total_uti_pediatrica

5111

# 24. UTI pediátrica SUS

 calculando  a quantidade total de leitos de UTI pediátrica destinados ao SUS.

 identificando  a capacidade de terapia intensiva pediátrica disponível para atendimento pelo SUS.

In [81]:
total_uti_pediatrica_SUS = int(
    hospi_gold['UTI_PEDIATRICO_SUS'].sum()
)

total_uti_pediatrica_SUS

1230

# 25. Percentual de UTI pediátrica SUS

 calculando  o percentual de leitos de UTI pediátrica destinados ao SUS em relação ao total de UTI pediátrica existente.

 entendendo  a participação do SUS na capacidade de terapia intensiva pediátrica.

In [82]:
percentual_uti_pediatrico_sus = (
    total_uti_pediatrica_SUS / total_uti_pediatrica
) * 100

percentual_uti_pediatrico_sus = round(
    percentual_uti_pediatrico_sus,2
)

percentual_uti_pediatrico_sus

24.07

# 26. UTI neonatal existente

 calculando a quantidade total de leitos de UTI neonatal existentes nos estabelecimentos analisados.

 identificando a capacidade hospitalar destinada ao atendimento intensivo de recém-nascidos.

In [83]:
total_uti_neonatal = int(
    hospi_gold['UTI_NEONATAL_EXIST'].sum()
)

total_uti_neonatal

8348

# 27. UTI neonatal SUS

 calculando  a quantidade total de leitos de UTI neonatal destinados ao SUS.

 identificando a capacidade de terapia intensiva neonatal disponível para atendimento pelo SUS.

In [84]:
total_uti_neonatal_sus = int(
    hospi_gold['UTI_NEONATAL_SUS'].sum()
)

total_uti_neonatal_sus

2332

# 28. Percentual de UTI neonatal SUS

calculando o percentual de leitos de UTI neonatal destinados ao SUS em relação ao total de UTI neonatal existente.

 entendendo a participação do SUS na capacidade de terapia intensiva neonatal.

In [85]:
percentual_uti_neonatal_sus = (
    total_uti_neonatal_sus / total_uti_neonatal
) * 100

percentual_uti_neonatal_sus = round(
    percentual_uti_neonatal_sus, 2
)

percentual_uti_neonatal_sus

27.93

# 29. UTI de queimados existente
 calculamdo a quantidade total de leitos de UTI para atendimento de pacientes com queimaduras existentes nos estabelecimentos analisados.

 identificando  a capacidade hospitalar disponível para atendimento intensivo especializado de pacientes com queimaduras.

In [86]:
total_uti_queimados = int(
    hospi_gold['UTI_QUEIMADO_EXIST'].sum()
)

total_uti_queimados

114

# 30. Percentual de UTI de queimados SUS

 calculando o percentual de leitos de UTI de queimados destinados ao SUS em relação ao total existente.

 identificar a participação do SUS na capacidade de atendimento intensivo especializado para pacientes com queimaduras.

In [87]:
total_uti_queimados_sus = (
    hospi_gold['UTI_QUEIMADO_SUS'].sum()
)

total_uti_queimados_sus

np.int64(60)

# 31. Percentual de UTI de queimados SUS

 calculando o  percentual de leitos de UTI de queimados destinados ao SUS em relação ao total existente.

 identificar a participação do SUS na capacidade de atendimento intensivo especializado para pacientes com queimaduras.

In [88]:
percentual_uti_queimados_sus = (
    total_uti_queimados_sus / total_uti_queimados
)* 100

percentual_uti_queimados_sus = round(
    percentual_uti_queimados_sus,2
)

percentual_uti_queimados_sus

np.float64(52.63)

# 32. UTI coronariana existente

 calculando a quantidade total de leitos de UTI coronariana existentes nos estabelecimentos analisados.

 identificando a capacidade hospitalar disponível para atendimento intensivo de pacientes com necessidades cardiológicas.

In [89]:
total_uti_coronariana = int(
    hospi_gold['UTI_CORONARIANA_EXIST'].sum()
)

total_uti_coronariana

1633

# 33. UTI coronariana SUS

 calculando a quantidade total de leitos de UTI coronariana destinados ao SUS.

 identificando a capacidade de terapia intensiva cardiológica disponível para atendimento pelo SUS.

In [90]:
total_uti_coronariana_sus = int(
    hospi_gold['UTI_CORONARIANA_SUS'].sum()
)

total_uti_coronariana_sus

102

# 34. Percentual de UTI coronariana SUS

 calculando  o percentual de leitos de UTI coronariana destinados ao SUS em relação ao total existente.

 entendendo  a participação do SUS na capacidade de atendimento de terapia intensiva cardiológica.

In [91]:
percentual_uti_coronariana_sus = round(
    (
        hospi_gold["UTI_CORONARIANA_SUS"].sum()
        / hospi_gold["UTI_CORONARIANA_EXIST"].sum()
    ) * 100,
    2
)

percentual_uti_coronariana_sus

np.float64(6.25)

# 35. Consolidação dos indicadores de UTI

 reunindo os principais indicadores de UTI calculados durante a análise em uma única estrutura.

 facilitando   a visualização, comparação e utilização dos indicadores posteriormente no Power BI.

In [92]:
indicadores_uti = pd.DataFrame({
    "TIPO_UTI": [
        "Adulto",
        "Pediátrica",
        "Neonatal",
        "Queimados",
        "Coronariana"
    ],
    "LEITOS_EXISTENTES": [
        hospi_gold["UTI_ADULTO_EXIST"].sum(),
        hospi_gold["UTI_PEDIATRICO_EXIST"].sum(),
        hospi_gold["UTI_NEONATAL_EXIST"].sum(),
        hospi_gold["UTI_QUEIMADO_EXIST"].sum(),
        hospi_gold["UTI_CORONARIANA_EXIST"].sum()
    ],
    "LEITOS_SUS": [
        hospi_gold["UTI_ADULTO_SUS"].sum(),
        hospi_gold["UTI_PEDIATRICO_SUS"].sum(),
        hospi_gold["UTI_NEONATAL_SUS"].sum(),
        hospi_gold["UTI_QUEIMADO_SUS"].sum(),
        hospi_gold["UTI_CORONARIANA_SUS"].sum()
    ]
})

indicadores_uti

      TIPO_UTI  LEITOS_EXISTENTES  LEITOS_SUS
0       Adulto              33748       10696
1   Pediátrica               5111        1230
2     Neonatal               8348        2332
3    Queimados                114          60
4  Coronariana               1633         102

# 36. Percentual de leitos SUS por tipo de UTI

 calculando o percentual de leitos destinados ao SUS para cada tipo de UTI.

 comparando a participação do SUS entre os diferentes tipos de atendimento intensivo.

In [93]:
indicadores_uti['PERCENTUAL_SUS']=(
    indicadores_uti['LEITOS_SUS'] / indicadores_uti['LEITOS_EXISTENTES']
)* 100

indicadores_uti['PERCENTUAL_SUS'] = (
    indicadores_uti['PERCENTUAL_SUS'].round(2)
)

indicadores_uti

      TIPO_UTI  LEITOS_EXISTENTES  LEITOS_SUS  PERCENTUAL_SUS
0       Adulto              33748       10696           31.69
1   Pediátrica               5111        1230           24.07
2     Neonatal               8348        2332           27.93
3    Queimados                114          60           52.63
4  Coronariana               1633         102            6.25

# 37. identificando UTI com maior participação do SUS

 identificando qual tipo de UTI possui o maior percentual de leitos destinados ao SUS.

 descobrindo  em qual categoria de UTI o SUS possui a maior participação proporcional.

In [94]:
maior_participacao_sus = indicadores_uti.loc[
    indicadores_uti['PERCENTUAL_SUS'].idxmax()
]

maior_participacao_sus

TIPO_UTI             Queimados
LEITOS_EXISTENTES          114
LEITOS_SUS                  60
PERCENTUAL_SUS           52.63
Name: 3, dtype: object

# 38. UTI com maior quantidade de leitos

 identificando qual tipo de UTI possui a maior quantidade de leitos existentes.

 descobrindo qual categoria de UTI representa a maior capacidade hospitalar disponível na base analisada.

In [95]:
maior_quantidade_leitos = indicadores_uti.loc[
    indicadores_uti['LEITOS_EXISTENTES'].idxmax()
]

maior_quantidade_leitos

TIPO_UTI             Adulto
LEITOS_EXISTENTES     33748
LEITOS_SUS            10696
PERCENTUAL_SUS        31.69
Name: 0, dtype: object

# 39. Comparação entre leitos existentes e leitos SUS

 comparando  a quantidade de leitos existentes com a quantidade de leitos destinados ao SUS em cada tipo de UTI.

 visualizando a diferença entre a capacidade total de cada tipo de UTI e a parcela destinada ao atendimento pelo SUS.

In [96]:
indicadores_uti['LEITOS_NAO_SUS'] = (
    indicadores_uti['LEITOS_EXISTENTES'] -
    indicadores_uti['LEITOS_SUS']
)

indicadores_uti

      TIPO_UTI  LEITOS_EXISTENTES  LEITOS_SUS  PERCENTUAL_SUS  LEITOS_NAO_SUS
0       Adulto              33748       10696           31.69           23052
1   Pediátrica               5111        1230           24.07            3881
2     Neonatal               8348        2332           27.93            6016
3    Queimados                114          60           52.63              54
4  Coronariana               1633         102            6.25            1531

# 40. UTI com maior quantidade de leitos SUS

 identificando  qual tipo de UTI possui a maior quantidade de leitos destinados ao SUS.

 descobrindo qual categoria de UTI possui a maior quantidade absoluta de leitos SUS na base hospitalar.

In [97]:
maior_quantidade_leitos_SUS = indicadores_uti.loc[
    indicadores_uti['LEITOS_SUS'].idxmax()
]

maior_quantidade_leitos_SUS

TIPO_UTI             Adulto
LEITOS_EXISTENTES     33748
LEITOS_SUS            10696
PERCENTUAL_SUS        31.69
LEITOS_NAO_SUS        23052
Name: 0, dtype: object

# 41. Ordenação das UTIs pelo percentual de leitos SUS

**O que vamos fazer:** ordenar os tipos de UTI do maior para o menor percentual de leitos destinados ao SUS.

**Para que serve:** facilitar a identificação das categorias com maior e menor participação proporcional do SUS.

In [98]:
uti_por_percentual_sus = indicadores_uti.sort_values(
    'PERCENTUAL_SUS',
    ascending=False
)

uti_por_percentual_sus

      TIPO_UTI  LEITOS_EXISTENTES  LEITOS_SUS  PERCENTUAL_SUS  LEITOS_NAO_SUS
3    Queimados                114          60           52.63              54
0       Adulto              33748       10696           31.69           23052
2     Neonatal               8348        2332           27.93            6016
1   Pediátrica               5111        1230           24.07            3881
4  Coronariana               1633         102            6.25            1531

# 42. UTI com menor participação do SUS

 identificando qual tipo de UTI possui o menor percentual de leitos destinados ao SUS.

 identificando a categoria de UTI com menor participação proporcional do SUS.

In [99]:
menor_participacao_sus = indicadores_uti.loc[
    indicadores_uti['PERCENTUAL_SUS'].idxmin()
]

menor_participacao_sus

TIPO_UTI             Coronariana
LEITOS_EXISTENTES           1633
LEITOS_SUS                   102
PERCENTUAL_SUS              6.25
LEITOS_NAO_SUS              1531
Name: 4, dtype: object

# 43. Resumo dos indicadores de UTI

 criando  um resumo com os principais indicadores calculados para as UTIs.

 reunir os resultados mais importantes da análise em uma estrutura simples para interpretação e utilização posterior no Power BI.

In [100]:
resumo_uti ={
    'maior quantidade de leitos':
maior_quantidade_leitos['TIPO_UTI'],
    'maior quantidade leitos sus':
maior_quantidade_leitos_SUS['TIPO_UTI'],
    'maior participacao sus (%)':
maior_participacao_sus['TIPO_UTI'],
    'Menor participação sus (%)':
menor_participacao_sus['TIPO_UTI']
}

resumo_uti

{'maior quantidade de leitos': 'Adulto',
 'maior quantidade leitos sus': 'Adulto',
 'maior participacao sus (%)': 'Queimados',
 'Menor participação sus (%)': 'Coronariana'}

# 44. Tabela final dos principais indicadores

 transformando  resumo dos indicadores em uma tabela organizada.

 criando uma estrutura final que facilite a visualização dos principais resultados da análise e que poderá ser utilizada posteriormente no Power BI.

In [101]:
resumo_uti_df = pd.DataFrame({
    'INDICADOR':[
        'maior quantidade leitos',
        'maior quantidade leitos SUS',
        'maior participacao sus (%)',
        'menor participacao sus (%)'
    ],
    'RESULTADO':[
        maior_quantidade_leitos['TIPO_UTI'],
        maior_quantidade_leitos_SUS['TIPO_UTI'],
        maior_participacao_sus['TIPO_UTI'],
        menor_participacao_sus['TIPO_UTI']
    ]
})

resumo_uti_df

                     INDICADOR    RESULTADO
0      maior quantidade leitos       Adulto
1  maior quantidade leitos SUS       Adulto
2   maior participacao sus (%)    Queimados
3   menor participacao sus (%)  Coronariana

# 45. Verificação dos tipos de dados da tabela final

 verificando os tipos de dados das colunas da tabela final dos indicadores.

 confirmando que as informações estão armazenadas corretamente antes de utilizar essa tabela em outras etapas do projeto.

In [102]:
resumo_uti_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   INDICADOR  4 non-null      str
 1   RESULTADO  4 non-null      str
dtypes: str(2)
memory usage: 330.0 bytes

# 46. Visualização da tabela final dos indicadores

 visualizando  a tabela final dos principais indicadores de UTI.

 conferindo  os resultados consolidados antes de finalizar essa parte da análise.

In [103]:
resumo_uti_df

                     INDICADOR    RESULTADO
0      maior quantidade leitos       Adulto
1  maior quantidade leitos SUS       Adulto
2   maior participacao sus (%)    Queimados
3   menor participacao sus (%)  Coronariana

# 47. Verificação de valores nulos nos indicadores finais

 verificando se a tabela final de indicadores possui valores ausentes.

 garantindo que a tabela esteja completa antes de ser utilizada no Power BI ou exportada para a camada Gold.

In [104]:
resumo_uti_df.isnull().sum()

INDICADOR    0
RESULTADO    0
dtype: int64

# 48. Criação da tabela Gold de indicadores de UTI

criando uma tabela final contendo os principais indicadores de UTI calculados durante a análise.

 organizando os resultados em uma estrutura própria para análise e visualização no Power BI.

In [105]:
gold_indicadores_uti = indicadores_uti.copy()
gold_indicadores_uti

      TIPO_UTI  LEITOS_EXISTENTES  LEITOS_SUS  PERCENTUAL_SUS  LEITOS_NAO_SUS
0       Adulto              33748       10696           31.69           23052
1   Pediátrica               5111        1230           24.07            3881
2     Neonatal               8348        2332           27.93            6016
3    Queimados                114          60           52.63              54
4  Coronariana               1633         102            6.25            1531

# 49. Verificação da tabela Gold de indicadores

 verificando  a estrutura e os tipos de dados da tabela final de indicadores
 garantindobo que a tabela esteja correta antes de exportá-la e utilizá-la no Power BI.

In [106]:
gold_indicadores_uti.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   TIPO_UTI           5 non-null      str
 1   LEITOS_EXISTENTES  5 non-null      int64
 2   LEITOS_SUS         5 non-null      int64
 3   PERCENTUAL_SUS     5 non-null      float64
 4   LEITOS_NAO_SUS     5 non-null      int64
dtypes: float64(1), int64(3), str(1)
memory usage: 377.0 bytes

# 50. Verificação de valores nulos na tabela Gold

 verificando se existem valores ausentes na tabela de indicadores de UTI.

 garantir a qualidade dos dados antes da exportação para o Power BI.

In [107]:
gold_indicadores_uti.isnull().sum()

TIPO_UTI             0
LEITOS_EXISTENTES    0
LEITOS_SUS           0
PERCENTUAL_SUS       0
LEITOS_NAO_SUS       0
dtype: int64

# 51. Verificação de valores duplicados

 verificando xistem registros duplicados na tabela Gold de indicadores de UTI.

 garantindo cada tipo de UTI apareça apenas uma vez na tabela final.

In [108]:
gold_indicadores_uti.duplicated().sum()

np.int64(0)

# 52. Ordenação da tabela Gold por quantidade de leitos

 ordenand os tipos de UTI do maior para o menor número de leitos existentes.

 facilitando  identificação das categorias com maior capacidade hospitalar.

In [109]:
gold_indicadores_uti = gold_indicadores_uti.sort_values(
    'LEITOS_EXISTENTES',
    ascending=False
)

gold_indicadores_uti

      TIPO_UTI  LEITOS_EXISTENTES  LEITOS_SUS  PERCENTUAL_SUS  LEITOS_NAO_SUS
0       Adulto              33748       10696           31.69           23052
2     Neonatal               8348        2332           27.93            6016
1   Pediátrica               5111        1230           24.07            3881
4  Coronariana               1633         102            6.25            1531
3    Queimados                114          60           52.63              54

# 53. Ordenação da tabela Gold pelo percentual SUS

 ordenando os tipos de UTI do maior para o menor percentual de leitos destinados ao SUS.

 facilitando a identificação das UTIs com maior e menor participação proporcional do SUS.

In [110]:
gold_uti_por_percentual = gold_indicadores_uti.sort_values(
    'PERCENTUAL_SUS',
    ascending=False
)

gold_uti_por_percentual

      TIPO_UTI  LEITOS_EXISTENTES  LEITOS_SUS  PERCENTUAL_SUS  LEITOS_NAO_SUS
3    Queimados                114          60           52.63              54
0       Adulto              33748       10696           31.69           23052
2     Neonatal               8348        2332           27.93            6016
1   Pediátrica               5111        1230           24.07            3881
4  Coronariana               1633         102            6.25            1531

# 54. Criação da tabela Gold final

 criando uma cópia da tabela de indicadores de UTI para preservar a versão final dos dados.

 manter uma tabela Gold final organizada e independente das transformações realizadas durante a análise.

In [111]:
gold_final_uti = gold_uti_por_percentual.copy()
gold_final_uti

      TIPO_UTI  LEITOS_EXISTENTES  LEITOS_SUS  PERCENTUAL_SUS  LEITOS_NAO_SUS
3    Queimados                114          60           52.63              54
0       Adulto              33748       10696           31.69           23052
2     Neonatal               8348        2332           27.93            6016
1   Pediátrica               5111        1230           24.07            3881
4  Coronariana               1633         102            6.25            1531

# 55. Verificação da tabela Gold final

verificando a estrutura da tabela final de indicadores de UTI antes de exportá-la.

 confirmando que a tabela Gold está organizada e pronta para ser utilizada nas próximas etapas do projeto.

In [112]:
gold_final_uti.info()

<class 'pandas.DataFrame'>
Index: 5 entries, 3 to 4
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   TIPO_UTI           5 non-null      str
 1   LEITOS_EXISTENTES  5 non-null      int64
 2   LEITOS_SUS         5 non-null      int64
 3   PERCENTUAL_SUS     5 non-null      float64
 4   LEITOS_NAO_SUS     5 non-null      int64
dtypes: float64(1), int64(3), str(1)
memory usage: 286.0 bytes

# 56. Verificação de valores nulos na Gold final

 verificando se existem valores ausentes na tabela Gold final de indicadores de UTI.

 garantindo que os dados estejam completos antes de salvar a tabela e utilizá-la no Power BI.

In [113]:
gold_final_uti.isnull().sum()

TIPO_UTI             0
LEITOS_EXISTENTES    0
LEITOS_SUS           0
PERCENTUAL_SUS       0
LEITOS_NAO_SUS       0
dtype: int64

# 57. Verificação de registros duplicados na Gold final

 verificando se existem registros duplicados na tabela Gold final de indicadores de UTI.

 garantindo que cada tipo de UTI esteja representado uma única vez na tabela final.

In [114]:
gold_final_uti.duplicated().sum()

np.int64(0)

# 58. Conferência dos valores finais da Gold

 visualização da tabela Gold final para conferir os valores dos principais indicadores de UTI.

 realizando uma última conferência dos dados antes de finalizar essa parte do processo e preparar a tabela para utilização no Power BI.

In [129]:
gold_final_uti

      TIPO_UTI  LEITOS_EXISTENTES  LEITOS_SUS  PERCENTUAL_SUS  LEITOS_NAO_SUS
3    Queimados                114          60           52.63              54
0       Adulto              33748       10696           31.69           23052
2     Neonatal               8348        2332           27.93            6016
1   Pediátrica               5111        1230           24.07            3881
4  Coronariana               1633         102            6.25            1531

# 59. Exportação da tabela Gold para CSV

 salvar a tabela final de indicadores de UTI em formato CSV dentro da pasta Gold.

 criando um arquivo final da camada Gold que poderá ser utilizado posteriormente no Power BI, SQL ou outras ferramentas de análise.

In [116]:
gold_final_uti.to_csv(
    r'C:\Users\lokiz\OneDrive\Documentos\projeto_hospitalar_rio\03_GOLD\gold_final_uti.csv',
    index=False,
    encoding='utf-8-sig'
)

# 60. Verificação do arquivo Gold exportado

 confirmando que o arquivo CSV da camada Gold foi criado corretamente.

 garantir que o arquivo final está disponível antes de avançarmos para a próxima etapa do projeto.

In [117]:
import os
os.path.exists(
    r'C:\Users\lokiz\OneDrive\Documentos\projeto_hospitalar_rio\03_GOLD\gold_final_uti.csv'
)

True

# 61. Validação do arquivo Gold exportado

 carregando novamente o arquivo CSV que foi exportado para a pasta Gold.

 confirmando que os dados foram gravados corretamente no arquivo e podem ser utilizados posteriormente no Power BI.

In [118]:
gold_final_uti_csv = pd.read_csv(
    r'C:\Users\lokiz\OneDrive\Documentos\projeto_hospitalar_rio\03_GOLD\gold_final_uti.csv'
)
gold_final_uti_csv

      TIPO_UTI  LEITOS_EXISTENTES  LEITOS_SUS  PERCENTUAL_SUS  LEITOS_NAO_SUS
0    Queimados                114          60           52.63              54
1       Adulto              33748       10696           31.69           23052
2     Neonatal               8348        2332           27.93            6016
3   Pediátrica               5111        1230           24.07            3881
4  Coronariana               1633         102            6.25            1531

# 62. Comparação entre a tabela Gold e o arquivo exportado

 comparando a quantidade de registros e colunas da tabela original com o arquivo CSV que foi salvo.

 confirmando que nenhum registro ou coluna foi perdido durante a exportação.

In [119]:
gold_final_uti_csv.shape,gold_final_uti_csv.shape

((5, 5), (5, 5))

# 63. Conferência dos dados do arquivo Gold exportado

 visualizar os dados que foram carregados novamente a partir do arquivo CSV.

 confirmando que os valores dos indicadores permaneceram corretos após a exportação.

In [120]:
gold_final_uti_csv

      TIPO_UTI  LEITOS_EXISTENTES  LEITOS_SUS  PERCENTUAL_SUS  LEITOS_NAO_SUS
0    Queimados                114          60           52.63              54
1       Adulto              33748       10696           31.69           23052
2     Neonatal               8348        2332           27.93            6016
3   Pediátrica               5111        1230           24.07            3881
4  Coronariana               1633         102            6.25            1531

# 64. Verificação dos tipos de dados do arquivo Gold exportado

 verificando os tipos de dados das colunas após a leitura do arquivo CSV.

 confirmando que os dados foram carregados corretamente e estão prontos para serem utilizados em ferramentas de análise.

In [121]:
gold_final_uti_csv.dtypes

TIPO_UTI                 str
LEITOS_EXISTENTES      int64
LEITOS_SUS             int64
PERCENTUAL_SUS       float64
LEITOS_NAO_SUS         int64
dtype: object

# 65. Verificação de valores nulos após a exportação

verificando se o arquivo CSV exportado possui valores ausentes.

 garantindo que nenhum dado tenha sido perdido durante o processo de exportação e leitura do arquivo.

In [122]:
gold_final_uti_csv.isnull().sum()

TIPO_UTI             0
LEITOS_EXISTENTES    0
LEITOS_SUS           0
PERCENTUAL_SUS       0
LEITOS_NAO_SUS       0
dtype: int64

# 66. Verificação de registros duplicados após a exportação

 verificando se o arquivo Gold exportado possui registros duplicados.

 confirmando que a exportação não criou registros repetidos e que cada tipo de UTI continua aparecendo corretamente.

In [123]:
gold_final_uti_csv.duplicated().sum()

np.int64(0)

# 67. Conferência da estrutura do arquivo Gold exportado

 verificando a quantidade de linhas e colunas do arquivo Gold depois da exportação.

 confirmando que o arquivo continua com a estrutura esperada e que nenhum registro ou coluna foi perdido.

In [124]:
gold_final_uti_csv.shape

(5, 5)

# 68. Conferência final das colunas da Gold

 verificando os nomes das colunas presentes no arquivo Gold final.

 confirmando que a tabela possui somente as informações necessárias para a análise dos indicadores de UTI.

In [125]:
gold_final_uti_csv.columns.tolist()

['TIPO_UTI',
 'LEITOS_EXISTENTES',
 'LEITOS_SUS',
 'PERCENTUAL_SUS',
 'LEITOS_NAO_SUS']

# 69. Resumo final dos indicadores da Gold

apresentando os principais resultados encontrados na análise das UTIs.

 registro das principais descobertas da camada Gold e facilitar a interpretação dos dados antes da utilização no Power BI.

In [126]:
resumo_final_gold = {
    "Total de tipos de UTI": gold_final_uti_csv["TIPO_UTI"].nunique(),
    "Maior quantidade de leitos": gold_final_uti_csv.loc[
        gold_final_uti_csv["LEITOS_EXISTENTES"].idxmax(),
        "TIPO_UTI"
    ],
    "Maior quantidade de leitos SUS": gold_final_uti_csv.loc[
        gold_final_uti_csv["LEITOS_SUS"].idxmax(),
        "TIPO_UTI"
    ],
    "Maior percentual SUS": gold_final_uti_csv.loc[
        gold_final_uti_csv["PERCENTUAL_SUS"].idxmax(),
        "TIPO_UTI"
    ],
    "Menor percentual SUS": gold_final_uti_csv.loc[
        gold_final_uti_csv["PERCENTUAL_SUS"].idxmin(),
        "TIPO_UTI"
    ]
}

resumo_final_gold

{'Total de tipos de UTI': 5,
 'Maior quantidade de leitos': 'Adulto',
 'Maior quantidade de leitos SUS': 'Adulto',
 'Maior percentual SUS': 'Queimados',
 'Menor percentual SUS': 'Coronariana'}

#  70. Validação final do arquivo Gold

confirmando que o arquivo Gold possui a estrutura, os dados e a quantidade de registros esperados.

 garantindo que o arquivo está pronto para ser utilizado no Power BI e nas próximas etapas do projeto.

In [127]:
print("Linhas e colunas:", gold_final_uti_csv.shape)
print("Valores nulos:")
print(gold_final_uti_csv.isnull().sum())
print("Duplicados:", gold_final_uti_csv.duplicated().sum())
print("Colunas:", gold_final_uti_csv.columns.tolist())

Linhas e colunas: (5, 5)
Valores nulos:
TIPO_UTI             0
LEITOS_EXISTENTES    0
LEITOS_SUS           0
PERCENTUAL_SUS       0
LEITOS_NAO_SUS       0
dtype: int64
Duplicados: 0
Colunas: ['TIPO_UTI', 'LEITOS_EXISTENTES', 'LEITOS_SUS', 'PERCENTUAL_SUS', 'LEITOS_NAO_SUS']

# 71. Encerramento da camada Gold

 finalizando a camada Gold registrando o que foi realizado e quais resultados foram obtidos.

 documentar o processo de transformação dos dados e deixar a tabela final pronta para utilização no Power BI e nas próximas etapas do projeto.

In [128]:
gold_final_uti_csv

      TIPO_UTI  LEITOS_EXISTENTES  LEITOS_SUS  PERCENTUAL_SUS  LEITOS_NAO_SUS
0    Queimados                114          60           52.63              54
1       Adulto              33748       10696           31.69           23052
2     Neonatal               8348        2332           27.93            6016
3   Pediátrica               5111        1230           24.07            3881
4  Coronariana               1633         102            6.25            1531

## Resumo da Camada Gold

Nesta etapa, os dados tratados na camada Silver foram utilizados para gerar indicadores hospitalares relacionados aos leitos de UTI.

Foram analisados os leitos existentes, os leitos destinados ao SUS, o percentual de participação do SUS e os leitos não SUS por tipo de UTI.

A análise identificou que a UTI Adulto possui a maior quantidade de leitos existentes e também a maior quantidade absoluta de leitos SUS. A UTI de Queimados apresentou a maior participação proporcional do SUS, enquanto a UTI Coronariana apresentou a menor participação proporcional.

Após as análises, os dados foram validados quanto a valores nulos, registros duplicados, estrutura e tipos de dados. A tabela final foi exportada para o arquivo `gold_final_uti.csv`, ficando pronta para utilização no Power BI e nas próximas etapas do projeto.