##  Camada Silver — Tratamento dos Dados

Nesta etapa, vamos trabalhar com os dados provenientes da camada Bronze.

O objetivo é realizar o tratamento, limpeza e padronização dos dados, preparando-os para a camada Gold e para as análises posteriores.

O arquivo original da camada Bronze será preservado e nenhuma alteração será realizada diretamente nele.

## Importação das bibliotecas pandas

Para realizar o tratamento dos dados, utilizaremos a biblioteca Pandas.

O Pandas permite carregar arquivos, visualizar informações, identificar problemas e realizar transformações em tabelas de dados.

## Carregamento dos dados da camada Bronze

Nesta etapa, vamos carregar o arquivo original "Leitos_2026.csv", armazenado na camada Bronze.

O arquivo será utilizado como fonte para o processo de tratamento da camada Silver.

O arquivo original não será modificado.

In [1]:
import pandas as pd
hospi_bronze = pd.read_csv(r"C:\Users\lokiz\OneDrive\Documentos\projeto_hospitalar_rio\01_BRONZE\Leitos_2026.csv", sep=';', encoding='latin1')
hospi_bronze

,COMP,REGIAO,UF,CO_IBGE,MUNICIPIO,MOTIVO_DESABILITACAO,CNES,NOME_ESTABELECIMENTO,RAZAO_SOCIAL,TP_GESTAO,...,UTI_ADULTO_EXIST,UTI_ADULTO_SUS,UTI_PEDIATRICO_EXIST,UTI_PEDIATRICO_SUS,UTI_NEONATAL_EXIST,UTI_NEONATAL_SUS,UTI_QUEIMADO_EXIST,UTI_QUEIMADO_SUS,UTI_CORONARIANA_EXIST,UTI_CORONARIANA_SUS
0,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,27,CASA DE SAUDE SANTA HELENA,CASA DE SAUDE E MATERNIDADE SANTA HELENA LTDA,M,...,0,0,0,0,0,0,0,0,0,0
1,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,35,HOSPITAL MENDO SAMPAIO,PREFEITURA MUNICIPAL DO CABO DE SANTO AGOSTINHO,M,...,0,0,0,0,0,0,0,0,0,0
2,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,94,MATERNIDADE PADRE GERALDO LEITE BASTOS,PREFEITURA MUNICIPAL DO CABO DE SANTO AGOSTINHO,M,...,0,0,0,0,0,0,0,0,0,0
3,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,183,HOSPITAL SAMARITANO,SOCIEDADE HOSPITALAR SAMARITANO LTDA,M,...,0,0,0,0,0,0,0,0,0,0
4,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,221,HOSPITAL SAO SEBASTIAO,CASA DE SAUDE E MATERNIDADE SAO SEBASTIAO LTDA,M,...,10,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43175,202606,NORDESTE,PB,250970,MONTEIRO,NaN,9954279,HOSPITAL DIA SANTA MARIA,CENTRO MEDICO MAYER E FEITOSA LTDA,M,...,0,0,0,0,0,0,0,0,0,0
43176,202606,SUDESTE,SP,355060,SAO ROQUE,NaN,9966900,HOSPITAL SAO FRANCISCO,HOSPITAL SAO FRANCISCO EIRELI,M,...,0,0,0,0,0,0,0,0,0,0
43177,202606,SUDESTE,SP,352250,ITAPEVI,NaN,9997032,HOSPITAL YES,HOSPITAL YES LTDA,M,...,40,0,0,0,0,0,0,0,0,0
43178,202606,NORDESTE,PB,250460,CONDE,NaN,9997172,CLINICA MEDICA PERSONNALITE,CLINICA MEDICA PERSONNALITE LTDA,M,...,0,0,0,0,0,0,0,0,0,0
43179,202606,NORDESTE,MA,210125,BACABEIRA,NaN,9997784,HOSPITAL E MATERNIDADE NAILA GONCALO,MUNICIPIO DE BACABAEIRA,M,...,0,0,0,0,0,0,0,0,0,0

## 1. Visualização dos primeiros registros

visualizar as primeiras linhas do arquivo.

verificar se os dados foram carregados corretamente e conhecer inicialmente a estrutura das informações.

In [2]:
hospi_bronze.head()

,COMP,REGIAO,UF,CO_IBGE,MUNICIPIO,MOTIVO_DESABILITACAO,CNES,NOME_ESTABELECIMENTO,RAZAO_SOCIAL,TP_GESTAO,...,UTI_ADULTO_EXIST,UTI_ADULTO_SUS,UTI_PEDIATRICO_EXIST,UTI_PEDIATRICO_SUS,UTI_NEONATAL_EXIST,UTI_NEONATAL_SUS,UTI_QUEIMADO_EXIST,UTI_QUEIMADO_SUS,UTI_CORONARIANA_EXIST,UTI_CORONARIANA_SUS
0,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,27,CASA DE SAUDE SANTA HELENA,CASA DE SAUDE E MATERNIDADE SANTA HELENA LTDA,M,...,0,0,0,0,0,0,0,0,0,0
1,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,35,HOSPITAL MENDO SAMPAIO,PREFEITURA MUNICIPAL DO CABO DE SANTO AGOSTINHO,M,...,0,0,0,0,0,0,0,0,0,0
2,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,94,MATERNIDADE PADRE GERALDO LEITE BASTOS,PREFEITURA MUNICIPAL DO CABO DE SANTO AGOSTINHO,M,...,0,0,0,0,0,0,0,0,0,0
3,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,183,HOSPITAL SAMARITANO,SOCIEDADE HOSPITALAR SAMARITANO LTDA,M,...,0,0,0,0,0,0,0,0,0,0
4,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,221,HOSPITAL SAO SEBASTIAO,CASA DE SAUDE E MATERNIDADE SAO SEBASTIAO LTDA,M,...,10,0,0,0,0,0,0,0,0,0

# 2. Visualização dos últimos registros

 visualizar as últimas linhas do conjunto de dados.
 
 verificar o final do arquivo e confirmar que os registros foram carregados corretamente.

In [3]:
hospi_bronze.tail()

,COMP,REGIAO,UF,CO_IBGE,MUNICIPIO,MOTIVO_DESABILITACAO,CNES,NOME_ESTABELECIMENTO,RAZAO_SOCIAL,TP_GESTAO,...,UTI_ADULTO_EXIST,UTI_ADULTO_SUS,UTI_PEDIATRICO_EXIST,UTI_PEDIATRICO_SUS,UTI_NEONATAL_EXIST,UTI_NEONATAL_SUS,UTI_QUEIMADO_EXIST,UTI_QUEIMADO_SUS,UTI_CORONARIANA_EXIST,UTI_CORONARIANA_SUS
43175,202606,NORDESTE,PB,250970,MONTEIRO,NaN,9954279,HOSPITAL DIA SANTA MARIA,CENTRO MEDICO MAYER E FEITOSA LTDA,M,...,0,0,0,0,0,0,0,0,0,0
43176,202606,SUDESTE,SP,355060,SAO ROQUE,NaN,9966900,HOSPITAL SAO FRANCISCO,HOSPITAL SAO FRANCISCO EIRELI,M,...,0,0,0,0,0,0,0,0,0,0
43177,202606,SUDESTE,SP,352250,ITAPEVI,NaN,9997032,HOSPITAL YES,HOSPITAL YES LTDA,M,...,40,0,0,0,0,0,0,0,0,0
43178,202606,NORDESTE,PB,250460,CONDE,NaN,9997172,CLINICA MEDICA PERSONNALITE,CLINICA MEDICA PERSONNALITE LTDA,M,...,0,0,0,0,0,0,0,0,0,0
43179,202606,NORDESTE,MA,210125,BACABEIRA,NaN,9997784,HOSPITAL E MATERNIDADE NAILA GONCALO,MUNICIPIO DE BACABAEIRA,M,...,0,0,0,0,0,0,0,0,0,0

# 3. Verificação da dimensão dos dados

 verificar a quantidade de linhas e colunas do DataFrame.
 
 entender o tamanho do conjunto de dados antes de iniciar o tratamento.

In [4]:
hospi_bronze.shape

(43180, 35)

# 4. Identificação das colunas

 visualizar os nomes de todas as colunas disponíveis.
 
 conhecer as informações existentes no banco e identificar quais campos poderão ser utilizados no tratamento e na análise.

In [5]:
hospi_bronze.columns

Index(['COMP', 'REGIAO', 'UF', 'CO_IBGE', 'MUNICIPIO', 'MOTIVO_DESABILITACAO',
       'CNES', 'NOME_ESTABELECIMENTO', 'RAZAO_SOCIAL', 'TP_GESTAO',
       'CO_TIPO_UNIDADE', 'DS_TIPO_UNIDADE', 'NATUREZA_JURIDICA',
       'DESC_NATUREZA_JURIDICA', 'NO_LOGRADOURO', 'NU_ENDERECO',
       'NO_COMPLEMENTO', 'NO_BAIRRO', 'CO_CEP', 'NU_TELEFONE', 'NO_EMAIL',
       'LEITOS_EXISTENTES', 'LEITOS_SUS', 'UTI_TOTAL_EXIST', 'UTI_TOTAL_SUS',
       'UTI_ADULTO_EXIST', 'UTI_ADULTO_SUS', 'UTI_PEDIATRICO_EXIST',
       'UTI_PEDIATRICO_SUS', 'UTI_NEONATAL_EXIST', 'UTI_NEONATAL_SUS',
       'UTI_QUEIMADO_EXIST', 'UTI_QUEIMADO_SUS', 'UTI_CORONARIANA_EXIST',
       'UTI_CORONARIANA_SUS'],
      dtype='str')

# 5. Verificação da estrutura dos dados

 analisar informações gerais sobre o DataFrame.
 
 verificar tipos de dados, quantidade de valores preenchidos, quantidade de registros e memória utilizada.

In [6]:
hospi_bronze.info()

<class 'pandas.DataFrame'>
RangeIndex: 43180 entries, 0 to 43179
Data columns (total 35 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   COMP                    43180 non-null  int64
 1   REGIAO                  43180 non-null  str
 2   UF                      43180 non-null  str
 3   CO_IBGE                 43180 non-null  int64
 4   MUNICIPIO               43180 non-null  str
 5   MOTIVO_DESABILITACAO    0 non-null      float64
 6   CNES                    43180 non-null  int64
 7   NOME_ESTABELECIMENTO    43180 non-null  str
 8   RAZAO_SOCIAL            43180 non-null  str
 9   TP_GESTAO               43180 non-null  str
 10  CO_TIPO_UNIDADE         43180 non-null  int64
 11  DS_TIPO_UNIDADE         43180 non-null  str
 12  NATUREZA_JURIDICA       43180 non-null  int64
 13  DESC_NATUREZA_JURIDICA  43180 non-null  str
 14  NO_LOGRADOURO           43180 non-null  str
 15  NU_ENDERECO             43175 non-null  str
 16  NO_COMPLEMENTO          8529 non-null   str
 17  NO_BAIRRO               43180 non-null  str
 18  CO_CEP                  43180 non-null  int64
 19  NU_TELEFONE             38056 non-null  str
 20  NO_EMAIL                29570 non-null  str
 21  LEITOS_EXISTENTES       43180 non-null  int64
 22  LEITOS_SUS              43180 non-null  int64
 23  UTI_TOTAL_EXIST         43180 non-null  int64
 24  UTI_TOTAL_SUS           43180 non-null  int64
 25  UTI_ADULTO_EXIST        43180 non-null  int64
 26  UTI_ADULTO_SUS          43180 non-null  int64
 27  UTI_PEDIATRICO_EXIST    43180 non-null  int64
 28  UTI_PEDIATRICO_SUS      43180 non-null  int64
 29  UTI_NEONATAL_EXIST      43180 non-null  int64
 30  UTI_NEONATAL_SUS        43180 non-null  int64
 31  UTI_QUEIMADO_EXIST      43180 non-null  int64
 32  UTI_QUEIMADO_SUS        43180 non-null  int64
 33  UTI_CORONARIANA_EXIST   43180 non-null  int64
 34  UTI_CORONARIANA_SUS     43180 non-null  int64
dtypes: float64(1), int64(20), str(14)
memory usage: 19.1 MB

# 6. Verificação de valores ausentes

 identificar quantos valores ausentes existem em cada coluna.
 
 descobrir quais campos possuem informações incompletas e precisam ser analisados durante o tratamento.

In [7]:
hospi_bronze.isnull().sum()

COMP                          0
REGIAO                        0
UF                            0
CO_IBGE                       0
MUNICIPIO                     0
MOTIVO_DESABILITACAO      43180
CNES                          0
NOME_ESTABELECIMENTO          0
RAZAO_SOCIAL                  0
TP_GESTAO                     0
CO_TIPO_UNIDADE               0
DS_TIPO_UNIDADE               0
NATUREZA_JURIDICA             0
DESC_NATUREZA_JURIDICA        0
NO_LOGRADOURO                 0
NU_ENDERECO                   5
NO_COMPLEMENTO            34651
NO_BAIRRO                     0
CO_CEP                        0
NU_TELEFONE                5124
NO_EMAIL                  13610
LEITOS_EXISTENTES             0
LEITOS_SUS                    0
UTI_TOTAL_EXIST               0
UTI_TOTAL_SUS                 0
UTI_ADULTO_EXIST              0
UTI_ADULTO_SUS                0
UTI_PEDIATRICO_EXIST          0
UTI_PEDIATRICO_SUS            0
UTI_NEONATAL_EXIST            0
UTI_NEONATAL_SUS              0
UTI_QUEIMADO_EXIST            0
UTI_QUEIMADO_SUS              0
UTI_CORONARIANA_EXIST         0
UTI_CORONARIANA_SUS           0
dtype: int64

# 7. Verificação de registros duplicados

 verificar se existem registros completamente duplicados.
 
 identificar registros repetidos que poderiam distorcer as análises.

In [8]:
hospi_bronze.duplicated().sum()

np.int64(0)

# 8. Percentual de valores ausentes

 calcular o percentual de valores ausentes em cada coluna.
 
 medir a proporção de dados faltantes e ajudar a decidir quais campos precisam de tratamento.

In [9]:
percentual_nulos = (
    hospi_bronze.isnull().sum()
    / len(hospi_bronze)
) * 100

percentual_nulos.sort_values(ascending=False)

MOTIVO_DESABILITACAO      100.000000
NO_COMPLEMENTO             80.247800
NO_EMAIL                   31.519222
NU_TELEFONE                11.866605
NU_ENDERECO                 0.011579
UTI_ADULTO_EXIST            0.000000
LEITOS_EXISTENTES           0.000000
LEITOS_SUS                  0.000000
UTI_TOTAL_EXIST             0.000000
UTI_TOTAL_SUS               0.000000
COMP                        0.000000
UTI_ADULTO_SUS              0.000000
UTI_PEDIATRICO_SUS          0.000000
UTI_NEONATAL_EXIST          0.000000
UTI_NEONATAL_SUS            0.000000
UTI_QUEIMADO_EXIST          0.000000
UTI_QUEIMADO_SUS            0.000000
UTI_CORONARIANA_EXIST       0.000000
UTI_PEDIATRICO_EXIST        0.000000
NO_BAIRRO                   0.000000
CO_CEP                      0.000000
REGIAO                      0.000000
NO_LOGRADOURO               0.000000
DESC_NATUREZA_JURIDICA      0.000000
NATUREZA_JURIDICA           0.000000
DS_TIPO_UNIDADE             0.000000
CO_TIPO_UNIDADE             0.000000
TP_GESTAO                   0.000000
RAZAO_SOCIAL                0.000000
NOME_ESTABELECIMENTO        0.000000
CNES                        0.000000
MUNICIPIO                   0.000000
CO_IBGE                     0.000000
UF                          0.000000
UTI_CORONARIANA_SUS         0.000000
dtype: float64

# 9. Criação da cópia para a camada Silver

 criar uma cópia dos dados da camada Bronze.
 
 realizar o tratamento na Silver sem modificar os dados originais da Bronze.

In [10]:
hospi_silver = hospi_bronze.copy()
hospi_silver

,COMP,REGIAO,UF,CO_IBGE,MUNICIPIO,MOTIVO_DESABILITACAO,CNES,NOME_ESTABELECIMENTO,RAZAO_SOCIAL,TP_GESTAO,...,UTI_ADULTO_EXIST,UTI_ADULTO_SUS,UTI_PEDIATRICO_EXIST,UTI_PEDIATRICO_SUS,UTI_NEONATAL_EXIST,UTI_NEONATAL_SUS,UTI_QUEIMADO_EXIST,UTI_QUEIMADO_SUS,UTI_CORONARIANA_EXIST,UTI_CORONARIANA_SUS
0,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,27,CASA DE SAUDE SANTA HELENA,CASA DE SAUDE E MATERNIDADE SANTA HELENA LTDA,M,...,0,0,0,0,0,0,0,0,0,0
1,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,35,HOSPITAL MENDO SAMPAIO,PREFEITURA MUNICIPAL DO CABO DE SANTO AGOSTINHO,M,...,0,0,0,0,0,0,0,0,0,0
2,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,94,MATERNIDADE PADRE GERALDO LEITE BASTOS,PREFEITURA MUNICIPAL DO CABO DE SANTO AGOSTINHO,M,...,0,0,0,0,0,0,0,0,0,0
3,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,183,HOSPITAL SAMARITANO,SOCIEDADE HOSPITALAR SAMARITANO LTDA,M,...,0,0,0,0,0,0,0,0,0,0
4,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,221,HOSPITAL SAO SEBASTIAO,CASA DE SAUDE E MATERNIDADE SAO SEBASTIAO LTDA,M,...,10,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43175,202606,NORDESTE,PB,250970,MONTEIRO,NaN,9954279,HOSPITAL DIA SANTA MARIA,CENTRO MEDICO MAYER E FEITOSA LTDA,M,...,0,0,0,0,0,0,0,0,0,0
43176,202606,SUDESTE,SP,355060,SAO ROQUE,NaN,9966900,HOSPITAL SAO FRANCISCO,HOSPITAL SAO FRANCISCO EIRELI,M,...,0,0,0,0,0,0,0,0,0,0
43177,202606,SUDESTE,SP,352250,ITAPEVI,NaN,9997032,HOSPITAL YES,HOSPITAL YES LTDA,M,...,40,0,0,0,0,0,0,0,0,0
43178,202606,NORDESTE,PB,250460,CONDE,NaN,9997172,CLINICA MEDICA PERSONNALITE,CLINICA MEDICA PERSONNALITE LTDA,M,...,0,0,0,0,0,0,0,0,0,0
43179,202606,NORDESTE,MA,210125,BACABEIRA,NaN,9997784,HOSPITAL E MATERNIDADE NAILA GONCALO,MUNICIPIO DE BACABAEIRA,M,...,0,0,0,0,0,0,0,0,0,0

# 10. Verificação da cópia da Silver

verificar se a cópia possui a mesma quantidade de linhas e colunas da Bronze.

confirmar que os dados foram copiados corretamente antes do tratamento.

In [11]:
hospi_silver.shape

(43180, 35)

# 11. Visualização dos dados da Silver

 visualizar os primeiros registros da cópia.
 
 confirmar que os dados estão disponíveis na camada Silver antes das transformações.

In [12]:
hospi_silver.head()

,COMP,REGIAO,UF,CO_IBGE,MUNICIPIO,MOTIVO_DESABILITACAO,CNES,NOME_ESTABELECIMENTO,RAZAO_SOCIAL,TP_GESTAO,...,UTI_ADULTO_EXIST,UTI_ADULTO_SUS,UTI_PEDIATRICO_EXIST,UTI_PEDIATRICO_SUS,UTI_NEONATAL_EXIST,UTI_NEONATAL_SUS,UTI_QUEIMADO_EXIST,UTI_QUEIMADO_SUS,UTI_CORONARIANA_EXIST,UTI_CORONARIANA_SUS
0,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,27,CASA DE SAUDE SANTA HELENA,CASA DE SAUDE E MATERNIDADE SANTA HELENA LTDA,M,...,0,0,0,0,0,0,0,0,0,0
1,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,35,HOSPITAL MENDO SAMPAIO,PREFEITURA MUNICIPAL DO CABO DE SANTO AGOSTINHO,M,...,0,0,0,0,0,0,0,0,0,0
2,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,94,MATERNIDADE PADRE GERALDO LEITE BASTOS,PREFEITURA MUNICIPAL DO CABO DE SANTO AGOSTINHO,M,...,0,0,0,0,0,0,0,0,0,0
3,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,183,HOSPITAL SAMARITANO,SOCIEDADE HOSPITALAR SAMARITANO LTDA,M,...,0,0,0,0,0,0,0,0,0,0
4,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,221,HOSPITAL SAO SEBASTIAO,CASA DE SAUDE E MATERNIDADE SAO SEBASTIAO LTDA,M,...,10,0,0,0,0,0,0,0,0,0

# 12. Verificação de duplicados na Silver

 verificar novamente se existem registros duplicados na cópia da Silver.

 confirmar a qualidade dos dados antes de continuar o tratamento.

In [13]:
hospi_silver.duplicated().sum()

np.int64(0)

# 13. Análise dos valores ausentes na Silver

verificar novamente os valores ausentes na camada Silver.

 analisar quais colunas possuem informações incompletas antes de decidir o tratamento.

In [14]:
hospi_silver.isnull().sum()

COMP                          0
REGIAO                        0
UF                            0
CO_IBGE                       0
MUNICIPIO                     0
MOTIVO_DESABILITACAO      43180
CNES                          0
NOME_ESTABELECIMENTO          0
RAZAO_SOCIAL                  0
TP_GESTAO                     0
CO_TIPO_UNIDADE               0
DS_TIPO_UNIDADE               0
NATUREZA_JURIDICA             0
DESC_NATUREZA_JURIDICA        0
NO_LOGRADOURO                 0
NU_ENDERECO                   5
NO_COMPLEMENTO            34651
NO_BAIRRO                     0
CO_CEP                        0
NU_TELEFONE                5124
NO_EMAIL                  13610
LEITOS_EXISTENTES             0
LEITOS_SUS                    0
UTI_TOTAL_EXIST               0
UTI_TOTAL_SUS                 0
UTI_ADULTO_EXIST              0
UTI_ADULTO_SUS                0
UTI_PEDIATRICO_EXIST          0
UTI_PEDIATRICO_SUS            0
UTI_NEONATAL_EXIST            0
UTI_NEONATAL_SUS              0
UTI_QUEIMADO_EXIST            0
UTI_QUEIMADO_SUS              0
UTI_CORONARIANA_EXIST         0
UTI_CORONARIANA_SUS           0
dtype: int64

# 14. Percentual de valores ausentes na Silver

 calcular novamente o percentual de valores ausentes na Silver.

 avaliar a dimensão dos dados faltantes e tomar decisões de tratamento com base nos resultados.

In [15]:
percentual_nulos = (
    hospi_silver.isnull().sum()
    / len(hospi_silver)
)* 100
percentual_nulos.sort_values(ascending=False)

MOTIVO_DESABILITACAO      100.000000
NO_COMPLEMENTO             80.247800
NO_EMAIL                   31.519222
NU_TELEFONE                11.866605
NU_ENDERECO                 0.011579
UTI_ADULTO_EXIST            0.000000
LEITOS_EXISTENTES           0.000000
LEITOS_SUS                  0.000000
UTI_TOTAL_EXIST             0.000000
UTI_TOTAL_SUS               0.000000
COMP                        0.000000
UTI_ADULTO_SUS              0.000000
UTI_PEDIATRICO_SUS          0.000000
UTI_NEONATAL_EXIST          0.000000
UTI_NEONATAL_SUS            0.000000
UTI_QUEIMADO_EXIST          0.000000
UTI_QUEIMADO_SUS            0.000000
UTI_CORONARIANA_EXIST       0.000000
UTI_PEDIATRICO_EXIST        0.000000
NO_BAIRRO                   0.000000
CO_CEP                      0.000000
REGIAO                      0.000000
NO_LOGRADOURO               0.000000
DESC_NATUREZA_JURIDICA      0.000000
NATUREZA_JURIDICA           0.000000
DS_TIPO_UNIDADE             0.000000
CO_TIPO_UNIDADE             0.000000
TP_GESTAO                   0.000000
RAZAO_SOCIAL                0.000000
NOME_ESTABELECIMENTO        0.000000
CNES                        0.000000
MUNICIPIO                   0.000000
CO_IBGE                     0.000000
UF                          0.000000
UTI_CORONARIANA_SUS         0.000000
dtype: float64

# 15. Remoção de coluna sem informações

 remover a coluna `MOTIVO_DESABILITACAO`, que não possui nenhum valor preenchido.

 eliminar uma coluna sem informação útil no conjunto analisado, reduzindo dados desnecessários e deixando a Silver mais organizada.

In [16]:
hospi_silver = hospi_silver.drop(
    columns=['MOTIVO_DESABILITACAO']
)

# 16. Verificação dos tipos de dados

 verificar novamente os tipos das colunas após as primeiras etapas de tratamento.

 identificar colunas que precisam ser convertidas para o tipo de dado adequado.

In [17]:
hospi_silver.dtypes

COMP                      int64
REGIAO                      str
UF                          str
CO_IBGE                   int64
MUNICIPIO                   str
CNES                      int64
NOME_ESTABELECIMENTO        str
RAZAO_SOCIAL                str
TP_GESTAO                   str
CO_TIPO_UNIDADE           int64
DS_TIPO_UNIDADE             str
NATUREZA_JURIDICA         int64
DESC_NATUREZA_JURIDICA      str
NO_LOGRADOURO               str
NU_ENDERECO                 str
NO_COMPLEMENTO              str
NO_BAIRRO                   str
CO_CEP                    int64
NU_TELEFONE                 str
NO_EMAIL                    str
LEITOS_EXISTENTES         int64
LEITOS_SUS                int64
UTI_TOTAL_EXIST           int64
UTI_TOTAL_SUS             int64
UTI_ADULTO_EXIST          int64
UTI_ADULTO_SUS            int64
UTI_PEDIATRICO_EXIST      int64
UTI_PEDIATRICO_SUS        int64
UTI_NEONATAL_EXIST        int64
UTI_NEONATAL_SUS          int64
UTI_QUEIMADO_EXIST        int64
UTI_QUEIMADO_SUS          int64
UTI_CORONARIANA_EXIST     int64
UTI_CORONARIANA_SUS       int64
dtype: object

# 17. Verificação dos estados

 visualizar os estados presentes no conjunto de dados.

 confirmar quais estados estão disponíveis antes de selecionar os registros do Rio de Janeiro.

In [18]:
hospi_silver['UF'].value_counts()

UF
SP    6161
MG    3981
BA    3742
RJ    2964
GO    2688
PR    2680
PE    2371
RS    1980
MA    1933
CE    1887
PA    1701
SC    1469
RN    1171
PB    1163
PI    1160
MT    1095
MS     736
ES     681
AM     678
RO     676
AL     588
TO     481
DF     399
SE     333
AC     204
AP     138
RR     120
Name: count, dtype: int64

# 18. Seleção dos dados do Rio de Janeiro

 selecionar somente os registros cuja UF seja `RJ`.

 criar o conjunto de dados específico do Rio de Janeiro para o foco da análise hospitalar.

In [19]:
hospi_silver = hospi_silver [
    hospi_silver['UF'] == 'RJ'
].copy()

## uma condição

Ela verifica quais registros pertencem ao Rio de Janeiro

In [20]:
hospi_silver['UF'] == 'RJ'

98       True
99       True
100      True
101      True
102      True
         ...
43142    True
43155    True
43156    True
43158    True
43163    True
Name: UF, Length: 2964, dtype: bool

# 19. Verificação dos dados do Rio de Janeiro

 verificar a quantidade de registros que permaneceram após o filtro do Rio de Janeiro.

 confirmar que o filtro foi aplicado corretamente.

In [21]:
hospi_silver.shape

(2964, 34)

# 20. Validação da unidade federativa

 confirmar que todos os registros restantes pertencem ao Rio de Janeiro.

 garantir que nenhum registro de outro estado permaneceu após o filtro.

In [22]:
hospi_silver['UF'].value_counts()

UF
RJ    2964
Name: count, dtype: int64

# 21. Verificação dos municípios

 analisar a quantidade de registros por município dentro do Rio de Janeiro.

 conhecer a distribuição dos estabelecimentos hospitalares entre os municípios.

In [33]:
hospi_silver['MUNICIPIO'].value_counts()

MUNICIPIO
RIO DE JANEIRO           1160
NITEROI                   192
CAMPOS DOS GOYTACAZES     114
DUQUE DE CAXIAS           106
SAO GONCALO                82
                         ...
ARMACAO DOS BUZIOS          6
RIO CLARO                   6
ITALVA                      6
CORDEIRO                    6
CARAPEBUS                   4
Name: count, Length: 87, dtype: int64

# 22. Validação dos valores ausentes

 verificar novamente os valores ausentes depois do tratamento e do filtro do Rio de Janeiro.

 confirmar a qualidade dos dados que serão exportados para a Silver.

In [23]:
hospi_silver.isnull().sum()

COMP                         0
REGIAO                       0
UF                           0
CO_IBGE                      0
MUNICIPIO                    0
CNES                         0
NOME_ESTABELECIMENTO         0
RAZAO_SOCIAL                 0
TP_GESTAO                    0
CO_TIPO_UNIDADE              0
DS_TIPO_UNIDADE              0
NATUREZA_JURIDICA            0
DESC_NATUREZA_JURIDICA       0
NO_LOGRADOURO                0
NU_ENDERECO                  0
NO_COMPLEMENTO            2278
NO_BAIRRO                    0
CO_CEP                       0
NU_TELEFONE                471
NO_EMAIL                   882
LEITOS_EXISTENTES            0
LEITOS_SUS                   0
UTI_TOTAL_EXIST              0
UTI_TOTAL_SUS                0
UTI_ADULTO_EXIST             0
UTI_ADULTO_SUS               0
UTI_PEDIATRICO_EXIST         0
UTI_PEDIATRICO_SUS           0
UTI_NEONATAL_EXIST           0
UTI_NEONATAL_SUS             0
UTI_QUEIMADO_EXIST           0
UTI_QUEIMADO_SUS             0
UTI_CORONARIANA_EXIST        0
UTI_CORONARIANA_SUS          0
dtype: int64

# 23. Validação dos registros duplicados

 verificar se existem registros duplicados no conjunto final.

 garantir que não existam duplicações antes da exportação dos dados tratados.

In [24]:
hospi_silver.duplicated().sum()

np.int64(0)

# 24. Verificação final da estrutura

 analisar a estrutura final do DataFrame Silver.

 confirmar a quantidade de registros, colunas, tipos de dados e valores preenchidos antes de salvar o arquivo.

In [25]:
hospi_silver.info()

<class 'pandas.DataFrame'>
Index: 2964 entries, 98 to 43163
Data columns (total 34 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   COMP                    2964 non-null   int64
 1   REGIAO                  2964 non-null   str
 2   UF                      2964 non-null   str
 3   CO_IBGE                 2964 non-null   int64
 4   MUNICIPIO               2964 non-null   str
 5   CNES                    2964 non-null   int64
 6   NOME_ESTABELECIMENTO    2964 non-null   str
 7   RAZAO_SOCIAL            2964 non-null   str
 8   TP_GESTAO               2964 non-null   str
 9   CO_TIPO_UNIDADE         2964 non-null   int64
 10  DS_TIPO_UNIDADE         2964 non-null   str
 11  NATUREZA_JURIDICA       2964 non-null   int64
 12  DESC_NATUREZA_JURIDICA  2964 non-null   str
 13  NO_LOGRADOURO           2964 non-null   str
 14  NU_ENDERECO             2964 non-null   str
 15  NO_COMPLEMENTO          686 non-null    str
 16  NO_BAIRRO               2964 non-null   str
 17  CO_CEP                  2964 non-null   int64
 18  NU_TELEFONE             2493 non-null   str
 19  NO_EMAIL                2082 non-null   str
 20  LEITOS_EXISTENTES       2964 non-null   int64
 21  LEITOS_SUS              2964 non-null   int64
 22  UTI_TOTAL_EXIST         2964 non-null   int64
 23  UTI_TOTAL_SUS           2964 non-null   int64
 24  UTI_ADULTO_EXIST        2964 non-null   int64
 25  UTI_ADULTO_SUS          2964 non-null   int64
 26  UTI_PEDIATRICO_EXIST    2964 non-null   int64
 27  UTI_PEDIATRICO_SUS      2964 non-null   int64
 28  UTI_NEONATAL_EXIST      2964 non-null   int64
 29  UTI_NEONATAL_SUS        2964 non-null   int64
 30  UTI_QUEIMADO_EXIST      2964 non-null   int64
 31  UTI_QUEIMADO_SUS        2964 non-null   int64
 32  UTI_CORONARIANA_EXIST   2964 non-null   int64
 33  UTI_CORONARIANA_SUS     2964 non-null   int64
dtypes: int64(20), str(14)
memory usage: 1.3 MB

# 25. Visualização dos dados tratados

 visualizar os primeiros registros do DataFrame final.

 realizar uma última inspeção visual antes de exportar os dados para a camada Silver.

In [26]:
hospi_silver.head()

,COMP,REGIAO,UF,CO_IBGE,MUNICIPIO,CNES,NOME_ESTABELECIMENTO,RAZAO_SOCIAL,TP_GESTAO,CO_TIPO_UNIDADE,...,UTI_ADULTO_EXIST,UTI_ADULTO_SUS,UTI_PEDIATRICO_EXIST,UTI_PEDIATRICO_SUS,UTI_NEONATAL_EXIST,UTI_NEONATAL_SUS,UTI_QUEIMADO_EXIST,UTI_QUEIMADO_SUS,UTI_CORONARIANA_EXIST,UTI_CORONARIANA_SUS
98,202601,SUDESTE,RJ,330330,NITEROI,12505,HOSPITAL UNIVERSITARIO ANTONIO PEDRO,EMPRESA BRASILEIRA DE SERVICOS HOSPITALARES,M,5,...,16,16,0,0,8,8,0,0,10,10
99,202601,SUDESTE,RJ,330330,NITEROI,12513,HOSPITAL MUNICIPAL CARLOS TORTELLY,FUNDACAO MUNICIPAL DE SAUDE,M,5,...,0,0,0,0,0,0,0,0,0,0
100,202601,SUDESTE,RJ,330330,NITEROI,12521,SES RJ HOSPITAL ESTADUAL AZEVEDO LIMA,SECRETARIA DE ESTADO DE SAUDE SES,E,5,...,35,30,0,0,10,0,0,0,0,0
101,202601,SUDESTE,RJ,330330,NITEROI,12548,HOSPITAL DA POLICIA MILITAR DE NITEROI,HOSPITAL DA POLICIA MILITAR DE NITEROI,M,5,...,0,0,0,0,0,0,0,0,0,0
102,202601,SUDESTE,RJ,330330,NITEROI,12556,HOSPITAL ORENCIO DE FREITAS,FUNDACAO MUNICIPAL DE SAUDE DE NITEROI,M,5,...,6,0,0,0,0,0,0,0,0,0

# 26. Exportação dos dados tratados para a camada Silver

 salvar os dados tratados em um novo arquivo CSV dentro da pasta Silver.

 criar o arquivo final da camada Silver, que será utilizado posteriormente na camada Gold, no SQL e no Power BI.

In [27]:
hospi_silver.to_csv(
    'leitos_2026_RJ_tratado.csv',
    index=False
)

# 27. Confirmação da exportação

 verificar se o arquivo tratado pode ser carregado novamente.

 confirmar que o arquivo da camada Silver foi salvo corretamente e pode ser utilizado nas próximas etapas do projeto.

In [28]:
hospi_silver_validado = pd.read_csv(
    'leitos_2026_RJ_tratado.csv'
)
hospi_silver_validado.head()

,COMP,REGIAO,UF,CO_IBGE,MUNICIPIO,CNES,NOME_ESTABELECIMENTO,RAZAO_SOCIAL,TP_GESTAO,CO_TIPO_UNIDADE,...,UTI_ADULTO_EXIST,UTI_ADULTO_SUS,UTI_PEDIATRICO_EXIST,UTI_PEDIATRICO_SUS,UTI_NEONATAL_EXIST,UTI_NEONATAL_SUS,UTI_QUEIMADO_EXIST,UTI_QUEIMADO_SUS,UTI_CORONARIANA_EXIST,UTI_CORONARIANA_SUS
0,202601,SUDESTE,RJ,330330,NITEROI,12505,HOSPITAL UNIVERSITARIO ANTONIO PEDRO,EMPRESA BRASILEIRA DE SERVICOS HOSPITALARES,M,5,...,16,16,0,0,8,8,0,0,10,10
1,202601,SUDESTE,RJ,330330,NITEROI,12513,HOSPITAL MUNICIPAL CARLOS TORTELLY,FUNDACAO MUNICIPAL DE SAUDE,M,5,...,0,0,0,0,0,0,0,0,0,0
2,202601,SUDESTE,RJ,330330,NITEROI,12521,SES RJ HOSPITAL ESTADUAL AZEVEDO LIMA,SECRETARIA DE ESTADO DE SAUDE SES,E,5,...,35,30,0,0,10,0,0,0,0,0
3,202601,SUDESTE,RJ,330330,NITEROI,12548,HOSPITAL DA POLICIA MILITAR DE NITEROI,HOSPITAL DA POLICIA MILITAR DE NITEROI,M,5,...,0,0,0,0,0,0,0,0,0,0
4,202601,SUDESTE,RJ,330330,NITEROI,12556,HOSPITAL ORENCIO DE FREITAS,FUNDACAO MUNICIPAL DE SAUDE DE NITEROI,M,5,...,6,0,0,0,0,0,0,0,0,0

# 28. Validação final da camada Silver

 verificar a quantidade final de registros e colunas do arquivo tratado.

 registrar a estrutura final da camada Silver e garantir que os dados estão prontos para a próxima etapa do projeto.

In [29]:
hospi_silver_validado.shape

(2964, 34)

In [30]:
hospi_silver_validado.info()

<class 'pandas.DataFrame'>
RangeIndex: 2964 entries, 0 to 2963
Data columns (total 34 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   COMP                    2964 non-null   int64
 1   REGIAO                  2964 non-null   str
 2   UF                      2964 non-null   str
 3   CO_IBGE                 2964 non-null   int64
 4   MUNICIPIO               2964 non-null   str
 5   CNES                    2964 non-null   int64
 6   NOME_ESTABELECIMENTO    2964 non-null   str
 7   RAZAO_SOCIAL            2964 non-null   str
 8   TP_GESTAO               2964 non-null   str
 9   CO_TIPO_UNIDADE         2964 non-null   int64
 10  DS_TIPO_UNIDADE         2964 non-null   str
 11  NATUREZA_JURIDICA       2964 non-null   int64
 12  DESC_NATUREZA_JURIDICA  2964 non-null   str
 13  NO_LOGRADOURO           2964 non-null   str
 14  NU_ENDERECO             2964 non-null   str
 15  NO_COMPLEMENTO          686 non-null    str
 16  NO_BAIRRO               2964 non-null   str
 17  CO_CEP                  2964 non-null   int64
 18  NU_TELEFONE             2493 non-null   str
 19  NO_EMAIL                2082 non-null   str
 20  LEITOS_EXISTENTES       2964 non-null   int64
 21  LEITOS_SUS              2964 non-null   int64
 22  UTI_TOTAL_EXIST         2964 non-null   int64
 23  UTI_TOTAL_SUS           2964 non-null   int64
 24  UTI_ADULTO_EXIST        2964 non-null   int64
 25  UTI_ADULTO_SUS          2964 non-null   int64
 26  UTI_PEDIATRICO_EXIST    2964 non-null   int64
 27  UTI_PEDIATRICO_SUS      2964 non-null   int64
 28  UTI_NEONATAL_EXIST      2964 non-null   int64
 29  UTI_NEONATAL_SUS        2964 non-null   int64
 30  UTI_QUEIMADO_EXIST      2964 non-null   int64
 31  UTI_QUEIMADO_SUS        2964 non-null   int64
 32  UTI_CORONARIANA_EXIST   2964 non-null   int64
 33  UTI_CORONARIANA_SUS     2964 non-null   int64
dtypes: int64(20), str(14)
memory usage: 1.3 MB

In [31]:
hospi_silver_validado.isnull().sum()

COMP                         0
REGIAO                       0
UF                           0
CO_IBGE                      0
MUNICIPIO                    0
CNES                         0
NOME_ESTABELECIMENTO         0
RAZAO_SOCIAL                 0
TP_GESTAO                    0
CO_TIPO_UNIDADE              0
DS_TIPO_UNIDADE              0
NATUREZA_JURIDICA            0
DESC_NATUREZA_JURIDICA       0
NO_LOGRADOURO                0
NU_ENDERECO                  0
NO_COMPLEMENTO            2278
NO_BAIRRO                    0
CO_CEP                       0
NU_TELEFONE                471
NO_EMAIL                   882
LEITOS_EXISTENTES            0
LEITOS_SUS                   0
UTI_TOTAL_EXIST              0
UTI_TOTAL_SUS                0
UTI_ADULTO_EXIST             0
UTI_ADULTO_SUS               0
UTI_PEDIATRICO_EXIST         0
UTI_PEDIATRICO_SUS           0
UTI_NEONATAL_EXIST           0
UTI_NEONATAL_SUS             0
UTI_QUEIMADO_EXIST           0
UTI_QUEIMADO_SUS             0
UTI_CORONARIANA_EXIST        0
UTI_CORONARIANA_SUS          0
dtype: int64

In [32]:
hospi_silver_validado.duplicated().sum()

np.int64(0)

# Resumo da Camada Silver

Nesta etapa, realizei o tratamento e a preparação dos dados hospitalares provenientes da camada Bronze.

Foram realizadas verificações da estrutura dos dados, valores ausentes e registros duplicados. Também foi criada uma cópia dos dados para preservar o arquivo original da camada Bronze.

A coluna `MOTIVO_DESABILITACAO`, que não possuía informações preenchidas, foi removida. Os campos `NO_COMPLEMENTO`, `NU_TELEFONE` e `NO_EMAIL` foram mantidos mesmo apresentando valores ausentes, pois essas informações não invalidam os registros dos estabelecimentos.

Em seguida, os dados foram filtrados para manter somente os estabelecimentos do estado do Rio de Janeiro (`UF = RJ`) e foram realizadas validações finais da qualidade e estrutura dos dados.

Por fim, os dados tratados foram exportados para:

`silver/Leitos_2026_RJ_tratado.csv`

A camada Silver está preparada para ser utilizada como base para a próxima etapa do projeto: a construção da camada Gold e posteriormente as análises em SQL e Power BI.